### ISSUE TITLE
problem with make install at asterisk asterisk-13.37.1

### ISSUE THREAD

**Issue by nahimov** [proquar/asterisk-Softmodem#2]
Hello! Could you please help me? When i make install asterisk i have error with app_softmodem.c i attach error at file.
[make_install_errors.txt](https://github.com/proquar/asterisk-Softmodem/files/5523404/make_install_errors.txt)

**Comment by nahimov** [comment]
I tried to make at Asterisk 16 and have this error also, one and one....

**Comment by proquar** [comment]
It seems you are trying to compile a html file. Try it with the C file.

**Comment by nahimov** [comment]
How i download file by wget from link: https://github.com/proquar/asterisk-Softmodem/blob/app_softmodem/app_softmodem.c

I check it right now....

**Comment by nahimov** [comment]
omg, my friend, you right....  It was a bad file, but right now i have an error with menuselect 

[root@on asterisk-16.14.1]# make apps
Generating input for menuselect ...
menuselect/menuselect --check-deps menuselect.makeopts

***********************************************************
  The existing menuselect.makeopts file did not specify
  that 'app_softmodem' should not be included.  However, either some
  dependencies for this module were not found or a
  conflict exists.

  Either run 'make menuselect' or remove the existing
  menuselect.makeopts file to resolve this issue.
***********************************************************

make: *** [menuselect.makeopts] Error 255
[root@on asterisk-16.14.1]# make menuselect
make[1]: Entering directory `/home/MrHunt/asterisk-16.14.1'
menuselect/menuselect --check-deps menuselect.makeopts

***********************************************************
  The existing menuselect.makeopts file did not specify
  that 'app_softmodem' should not be included.  However, either some
  dependencies for this module were not found or a
  conflict exists.

  Either run 'make menuselect' or remove the existing
  menuselect.makeopts file to resolve this issue.
***********************************************************

make[1]: *** [menuselect.makeopts] Error 255
make[1]: Leaving directory `/home/MrHunt/asterisk-16.14.1'
make: *** [menuselect] Error 2

**Comment by nahimov** [comment]
solve errors but not compile app_softmodem.c, and in menuselect from app_softmodem i see XXX

**Comment by nahimov** [comment]
Proquar, i fix it but i did not understand: "To fix, apply this patch to spandsp-0.0.6pre21.tgz source tree:" 
Were i must apply this patch ? I must set this code to some file? If yes on what file ?

**Comment by proquar** [comment]
No idea why you would need to patch spandsp, I just used whatever my distribution provided. Also I never tried this on Asterisk 16 and don't currently have any time or motivation to get it working there.
Here is a french tutorial from someone getting it to work in Asterisk 16: https://forum.museeminitel.fr/t/softmodem-asterisk-serveur/254

**Comment by nahimov** [comment]
solve this problem but have another. app_softmodem compiles well but asterisk can't load it. 

[root@on` modules]# find / -name app_softmodem.so
/usr/local/lib64/app_softmodem.so
/usr/lib64/asterisk/modules/app_softmodem.so

module placed at /usr/loca/lib64/ but when i try to load it at asterisk i have error:

on*CLI> module load app_softmodem
Unable to load module app_softmodem
Command 'module load app_softmodem' failed.
[Nov 12 20:50:00] ERROR[4287]: loader.c:281 module_load_error: Error loading module 'app_softmodem': libspandsp.so.2: cannot open shared object file: No such file or directory
on*CLI>

**Comment by proquar** [comment]
You'd have to find out where your asterisk modules are located on your system and put it there. Usually it's in some subdirectory of one of the lib directories, like /usr/loca/lib64/asterisk/. There should already be all the other modules from asterisk in there.

**Comment by nahimov** [comment]
I fix problem with lib, and module are loaded but when i call to phone i have error:

[Nov 15 21:22:46] WARNING[765][C-00000000]: app_softmodem.c:478 softmodem_communicate: Cannot connect to remote host.

**Comment by nahimov** [comment]
proquar hi! I start the module. When I call to number where softmodem is installed, when I pick up the phone, I should hear the modem sound, but I only hear silence.

**Comment by proquar** [comment]
You'd have to point it to some TCP server that speaks whatever protocol you want to communicate with. Can't help you with that, sorry.

**Comment by nahimov** [comment]
Why you think that i haven't point to some TCP ???
I have on this server at 127.0.0.1 by telnet port 23 and i see logs that port are opened for connection, only sound modem doesn't work for connect. 

You're not friendly at all...
