### ISSUE TITLE
Doesn't seem to work for me at all; I just get a continuous tone when I dial

### ISSUE THREAD

**Issue by xereeto** [proquar/asterisk-Softmodem#7]
Hey, bit of a long shot but I hope someone might be able to help me out with this. I'm using [johnnewcombe](https://github.com/johnnewcombe)'s fork with Asterisk 18.16.0 on Debian 10, and everything appears to work except that when I dial in I just get a continuous ~1300Hz tone which plays until I hang up. There's no error, and the softmodem does indeed make the connection to the remote server, but for some reason it will not even try to perform a handshake with the caller.

Any help with this would be massively appreciated, as unlikely as it may be that anyone will even read this lol

Cheers

**Comment by maxlock** [comment]
Hi @xereeto I've been trying to get app_softmodem working here recently too. Like you I've had no success either, with similar symptoms. Theres mention on the phreaktel group (https://groups.io/g/phreaknet/topic/89052653) of a replacement being worked on, but nothing beyond that.

**Comment by xereeto** [comment]
Welp... my solution was to buy a Cisco ATA and a real modem lol

**Comment by proquar** [comment]
Sounds like your modem is working just as expected.

The old modem standards don't do any kind of handshake, you have to configure the calling modem for the same mode as you have configured the asterisk app before calling. In fact back in the days of things like German BTX there just were different call-in numbers for the 4 or 5 supported standards.

The 1300 Hz tone you are hearing is just the mark frequency of the modem app, basically all it means it's not sending anything right now.

**Comment by xereeto** [comment]
...oh god lmfao i feel like a dumbass

**Comment by maxlock** [comment]
I kept at it, and discovered after adding the echo test app to Asterisk that I was only getting audio one way, from softmodem back to my modem. RTP packets weren't getting through and after digging in IOS a bit I enabled ip routing and everything now works.
